### ISSUE TITLE
请问纯ip的方式--verify-clients参数还管用吗

### ISSUE THREAD

**Issue by zhj9709** [veritas501/ip_derper#1]
![image](https://github.com/veritas501/ip_derper/assets/13991774/eefc3d01-e315-4753-a7b1-fc9d200d104a)
看到一个文章，写了纯ip模式不能防止被白嫖

**Comment by veritas501** [comment]
显然使用纯ip是不安全的，只是为了解决国内IP难备案的问题罢了

**Comment by zhj9709** [comment]
> 显然使用纯ip是不安全的，只是为了解决国内IP难备案的问题罢了

测试了一下，发现--verify-clients是有用的，也是可以防止白嫖的
